cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'codekitchen/dinghy'

brew 'ag'
brew 'ack'
brew 'automake'
brew 'autoconf'
brew 'coreutils'
brew 'dinghy'
brew 'docker'
brew 'docker-compose'
brew 'docker-machine'
brew 'fish'
brew 'git'
brew 'grc'
brew 'hub'
brew 'imagemagick'
brew 'ispell'
brew 'jp2a'
brew 'jq'
brew 'libgit2'
brew 'libyaml'
brew 'libtool'
brew 'libxslt'
brew 'nodenv'
brew 'openssl'
brew 'pyenv'
brew 'rbenv'
brew 'readline'
brew 'roundup'
brew 'spark'
brew 'unixodbc'
brew 'wget'
brew 'wxmac'
brew 'xhyve'
brew 'youtube-dl'

cask 'alfred'
cask 'emacs'
cask 'firefox'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'iterm2'
cask 'slack'
cask 'spectacle'
